<<<

[[_technicalSetup]]
== Technical Set-up

To add waitlist to your product page, you will need to do the following:

. Navigate to *User Interface*
. Click on *Items*
. Search for *waitlist* and open the edit tab for that item.
. Click on the *Pages* tab
. Assign the item to the pages you would like to utilize the module.
.. If you want to assign the item to the product page, assign the item to *PROD*.

Once you have assigned the item to the pages you would like, you can add the following code for the form and the reviews:

Add the following code where you want the Waitlist Form to display. *Do not add this inside of another form*:

[source,xml]
----
<mvt:if expr="g.Waitlist_Error"><div style="background: #e74c3c; color: #fff; font-size: 11px; padding: 5px 10px;">Error: &mvte:global:Waitlist_Error;</div></mvt:if>
<mvt:if expr="g.Waitlist_Message"><div style="background: #16a085; color: #fff; font-size: 11px; padding: 5px 10px;">&mvte:global:Waitlist_Message;</div></mvt:if>

<form name="waitlist_add" method="post" action="&mvte:product:link;" style="display:none;">
	<div style="font-size: 11px; background: #ecf0f1; text-align: center; padding: 10px 5px; margin-bottom: 0.75rem;">Sign up with your email to be notified when this product is back in stock!</div>
	<div id="jsWaitlist_Message"></div>
	<input type="hidden" name="Action" value="WaitlistAdd" />
	<input type="hidden" name="Waitlist_Product_Code" value="&mvt:product:code;" />
	<input type="hidden" name="Waitlist_Variant_ID" id="jsWaitlist_Variant_ID" value="&mvt:attributemachine:variant_id;" />
	<div style="display: flex;flex-direction: row;">
		<input type="email" name="Waitlist_Email" value="&mvte:global:Waitlist_Email;" placeholder="Email" style="flex: 1 1 auto; padding: 5px; border: 1px solid #bdc3c7; border-right: 0;" />
		<input type="submit" value="Sign up" class="button" style="flex: 1 1 auto; padding: 5px; border: 0; background-color: #3498db;" />
	</div>
</form>
----

Add the following code somewhere below the page, or utilize pieces of it to tie into your existing functionality (developers only):

[source,xml]
----
<mvt:item name="waitlist" param="Waitlist_API_URL( l.all_settings:waitlist_url )" />
----

[source,html]
----
<script>
	var waitlist_api = '&mvtj:waitlist_url;';
	// ---- Update Display When Attribute Machine Fires ---- //
	var waitlist_form = document.getElementsByName( 'waitlist_add' )[0];
	var waitlist_ajax_msg = document.getElementById( 'jsWaitlist_Message');
	if (typeof MivaEvents !== 'undefined') {
		MivaEvents.SubscribeToEvent('variant_changed', function (product_data) {
			var WaitlistVariantID = document.getElementById( 'jsWaitlist_Variant_ID' );
			if ( WaitlistVariantID ) {
				WaitlistVariantID.value = 0;
				if ( product_data.variant_id > 0 ) WaitlistVariantID.value = product_data.variant_id;
			}
			if ( am&mvte:product:id;.buttons && waitlist_form ) {
				var show_waitlist = 0;
				am&mvte:product:id;.buttons.forEach( function( button ) {
					if ( button.disabled ) show_waitlist = 1;
				});
				show_waitlist === 0 ? waitlist_form.style.display = 'none' : waitlist_form.style.display = 'block';
			}
		});
	}

	var stock_level = '&mvtj:attributemachine:product:inv_level;';
	( stock_level == 'out' && waitlist_form ) ? waitlist_form.style.display = 'block' : waitlist_form.style.display = 'none';

	// ---- Show / Hide Form for Attributes ---- //
	if ( typeof am&mvte:product:id; != 'undefined' ) {
		var inv_msg_element = document.getElementById( am&mvte:product:id;.settings.inventory_element_id );
		if ( inv_msg_element && ( inv_msg_element.innerHTML ).includes( am&mvte:product:id;.settings.invalid_msg ) && waitlist_form ) waitlist_form.style.display = 'none';
	}

	// Ajax Call
	if ( waitlist_form && waitlist_api ) {
		waitlist_form.onsubmit = function onSubmit( form ) {
			form.preventDefault();
			var Waitlist_Product_Code = document.getElementsByName( 'Waitlist_Product_Code' )[0].value;
			var Waitlist_Variant_ID = document.getElementsByName( 'Waitlist_Variant_ID' )[0].value;
			var Waitlist_Email = document.getElementsByName( 'Waitlist_Email' )[0].value;

			var waitlist_data = 'WaitlistFunction=Waitlist_Add&Product_Code=' + encodeURIComponent( Waitlist_Product_Code ) + '&Variant_ID=' + encodeURIComponent( Waitlist_Variant_ID ) + '&Email=' + encodeURIComponent( Waitlist_Email );

			var wishlist_call = new XMLHttpRequest();
			wishlist_call.open('POST', waitlist_api, true);
			wishlist_call.setRequestHeader("Content-type", "application/x-www-form-urlencoded");

			wishlist_call.onload = function() {
				if (this.status === 200) {
					var wishlist_return = JSON.parse( this.responseText );
					if ( wishlist_return.success === 0 ) {
						waitlist_ajax_msg.innerHTML = wishlist_return.error_message;
					} else {
						waitlist_ajax_msg.innerHTML = 'Thank you for signing up!';
					}
					console.log(wishlist_return);
				} else {
					waitlist_ajax_msg.innerHTML = 'An error has occurred.';
				}
			};
			wishlist_call.send( waitlist_data );

		}
	}
</script>
----

*Please Note:* If you are utilizing deferred attribute machine, you may have issues reading `attributemachine`.

